-- =========================
-- GOLNOTE - SUPABASE SCHEMA
-- =========================
-- Esegui questo script nel SQL Editor di Supabase.
-- Assicurati di avere l'estensione pgcrypto attiva.

create extension if not exists pgcrypto;

-- -------------------------
-- PROFILI APP (mister/player)
-- -------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('mister', 'player')),
  nickname text not null unique,
  display_nickname text,
  player_id bigint,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists display_nickname text;

-- -------------------------
-- TEAMS
-- -------------------------
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  color text not null,
  owner_user_id uuid not null references public.profiles(id) on delete cascade,
  password_hash text,
  created_at timestamptz not null default now(),
  unique (owner_user_id, name)
);

-- -------------------------
-- PLAYERS
-- -------------------------
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  number text not null,
  position text not null,
  team_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default now()
);

-- profili.player_id -> players.id
alter table public.profiles
  drop constraint if exists profiles_player_id_fkey;

alter table public.profiles
  add constraint profiles_player_id_fkey
  foreign key (player_id) references public.players(id) on delete set null;

-- -------------------------
-- FINES
-- -------------------------
create table if not exists public.fines (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  type text not null,
  amount numeric(10,2) not null,
  description text,
  due_date date not null,
  is_paid boolean not null default false,
  paid_at timestamptz,
  notification_id text,
  created_at timestamptz not null default now()
);

-- -------------------------
-- TRAINING SESSIONS
-- -------------------------
create table if not exists public.training_sessions (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  session_date date not null,
  title text,
  note text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- -------------------------
-- ATTENDANCE RECORDS
-- -------------------------
create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.training_sessions(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  status text not null check (status in (
    'present',
    'late',
    'absent_justified',
    'absent_unjustified',
    'injured'
  )),
  note text,
  updated_at timestamptz not null default now(),
  unique (session_id, player_id)
);

-- -------------------------
-- INDICI
-- -------------------------
create index if not exists idx_teams_owner on public.teams(owner_user_id);
create index if not exists idx_players_team on public.players(team_id);
create index if not exists idx_fines_player on public.fines(player_id);
create index if not exists idx_fines_due on public.fines(is_paid, due_date);
create index if not exists idx_sessions_team_date on public.training_sessions(team_id, session_date desc);
create index if not exists idx_attendance_session on public.attendance_records(session_id);
create index if not exists idx_attendance_player on public.attendance_records(player_id);

-- =========================
-- HELPER FUNCTIONS (RLS)
-- =========================
create or replace function public.current_player_id()
returns bigint
language sql
stable
security definer
set search_path = public, auth
as $$
  select p.player_id
  from public.profiles p
  where p.id = auth.uid()
$$;

create or replace function public.current_player_team_id()
returns bigint
language sql
stable
security definer
set search_path = public, auth
as $$
  select pl.team_id
  from public.players pl
  where pl.id = public.current_player_id()
$$;

create or replace function public.is_team_owner(team bigint)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.teams t
    where t.id = team
      and t.owner_user_id = auth.uid()
  )
$$;

-- =========================
-- RLS
-- =========================
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.players enable row level security;
alter table public.fines enable row level security;
alter table public.training_sessions enable row level security;
alter table public.attendance_records enable row level security;

-- PROFILES
drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles for insert
to authenticated
with check (id = auth.uid());

-- TEAMS
drop policy if exists teams_select_authenticated on public.teams;
create policy teams_select_authenticated
on public.teams for select
to authenticated
using (true);

drop policy if exists teams_insert_owner on public.teams;
create policy teams_insert_owner
on public.teams for insert
to authenticated
with check (owner_user_id = auth.uid());

drop policy if exists teams_update_owner on public.teams;
create policy teams_update_owner
on public.teams for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

drop policy if exists teams_delete_owner on public.teams;
create policy teams_delete_owner
on public.teams for delete
to authenticated
using (owner_user_id = auth.uid());

-- PLAYERS
drop policy if exists players_select_mister_or_same_team_player on public.players;
create policy players_select_mister_or_same_team_player
on public.players for select
to authenticated
using (
  public.is_team_owner(team_id)
  or team_id = public.current_player_team_id()
);

drop policy if exists players_insert_owner on public.players;
create policy players_insert_owner
on public.players for insert
to authenticated
with check (public.is_team_owner(team_id));

drop policy if exists players_update_owner on public.players;
create policy players_update_owner
on public.players for update
to authenticated
using (public.is_team_owner(team_id))
with check (public.is_team_owner(team_id));

drop policy if exists players_delete_owner on public.players;
create policy players_delete_owner
on public.players for delete
to authenticated
using (public.is_team_owner(team_id));

-- FINES
drop policy if exists fines_select_mister_or_self_player on public.fines;
create policy fines_select_mister_or_self_player
on public.fines for select
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and (
        public.is_team_owner(p.team_id)
        or p.id = public.current_player_id()
      )
  )
);

drop policy if exists fines_insert_owner on public.fines;
create policy fines_insert_owner
on public.fines for insert
to authenticated
with check (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
);

drop policy if exists fines_update_owner on public.fines;
create policy fines_update_owner
on public.fines for update
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
)
with check (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
);

drop policy if exists fines_delete_owner on public.fines;
create policy fines_delete_owner
on public.fines for delete
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
);

-- TRAINING SESSIONS
drop policy if exists sessions_select_mister_or_player_team on public.training_sessions;
create policy sessions_select_mister_or_player_team
on public.training_sessions for select
to authenticated
using (
  public.is_team_owner(team_id)
  or team_id = public.current_player_team_id()
);

drop policy if exists sessions_insert_owner on public.training_sessions;
create policy sessions_insert_owner
on public.training_sessions for insert
to authenticated
with check (
  public.is_team_owner(team_id)
  and created_by = auth.uid()
);

drop policy if exists sessions_update_owner on public.training_sessions;
create policy sessions_update_owner
on public.training_sessions for update
to authenticated
using (public.is_team_owner(team_id))
with check (public.is_team_owner(team_id));

drop policy if exists sessions_delete_owner on public.training_sessions;
create policy sessions_delete_owner
on public.training_sessions for delete
to authenticated
using (public.is_team_owner(team_id));

-- ATTENDANCE
drop policy if exists attendance_select_mister_or_self_player on public.attendance_records;
create policy attendance_select_mister_or_self_player
on public.attendance_records for select
to authenticated
using (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and (
        public.is_team_owner(s.team_id)
        or attendance_records.player_id = public.current_player_id()
      )
  )
);

drop policy if exists attendance_insert_owner on public.attendance_records;
create policy attendance_insert_owner
on public.attendance_records for insert
to authenticated
with check (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
);

drop policy if exists attendance_update_owner on public.attendance_records;
create policy attendance_update_owner
on public.attendance_records for update
to authenticated
using (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
)
with check (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
);

drop policy if exists attendance_delete_owner on public.attendance_records;
create policy attendance_delete_owner
on public.attendance_records for delete
to authenticated
using (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
);
