-- =========================
-- GOLNOTE - SUPABASE SCHEMA
-- =========================
-- Esegui questo script nel SQL Editor di Supabase.
-- Assicurati di avere l'estensione pgcrypto attiva.

create extension if not exists pgcrypto;

-- -------------------------
-- PROFILI APP (mister/player)
-- -------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('mister', 'player')),
  nickname text not null unique,
  display_nickname text,
  player_id bigint,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists display_nickname text;

-- -------------------------
-- TEAMS
-- -------------------------
create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  sport text not null default 'calcio',
  season_year text,
  category text,
  color text not null,
  logo_uri text,
  owner_user_id uuid not null references public.profiles(id) on delete cascade,
  password_hash text,
  mister_password text,
  created_at timestamptz not null default now(),
  unique (owner_user_id, name, season_year, category)
);

alter table public.teams
  add column if not exists logo_uri text;

alter table public.teams
  add column if not exists season_year text;

alter table public.teams
  add column if not exists category text;

alter table public.teams
  add column if not exists sport text;

update public.teams
set sport = 'calcio'
where sport is null;

alter table public.teams
  alter column sport set default 'calcio';

alter table public.teams
  alter column sport set not null;

alter table public.teams
  drop constraint if exists teams_sport_check;

alter table public.teams
  add constraint teams_sport_check
  check (sport in ('calcio', 'tennis', 'basket', 'pallavolo', 'baseball', 'rugby', 'hockey', 'ping pong'));

alter table public.teams
  add column if not exists mister_password text;

alter table public.teams
  drop constraint if exists teams_owner_user_id_name_key;

alter table public.teams
  drop constraint if exists teams_owner_name_season_category_key;

alter table public.teams
  drop constraint if exists teams_owner_name_sport_season_category_key;

alter table public.teams
  add constraint teams_owner_name_sport_season_category_key
  unique (owner_user_id, name, sport, season_year, category);

-- -------------------------
-- PLAYERS
-- -------------------------
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  surname text,
  number text not null,
  position text not null,
  team_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.players
  add column if not exists surname text;

-- profili.player_id -> players.id
alter table public.profiles
  drop constraint if exists profiles_player_id_fkey;

alter table public.profiles
  add constraint profiles_player_id_fkey
  foreign key (player_id) references public.players(id) on delete set null;

-- -------------------------
-- FINES
-- -------------------------
create table if not exists public.fines (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  type text not null,
  amount numeric(10,2) not null,
  description text,
  due_date date not null,
  is_paid boolean not null default false,
  paid_at timestamptz,
  notification_id text,
  created_at timestamptz not null default now()
);

-- -------------------------
-- TRAINING SESSIONS
-- -------------------------
create table if not exists public.training_sessions (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  session_date date not null,
  title text,
  note text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- -------------------------
-- ATTENDANCE RECORDS
-- -------------------------
create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.training_sessions(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  status text not null check (status in (
    'present',
    'late',
    'absent_justified',
    'absent_unjustified',
    'injured',
    'sick',
    'riposo'
  )),
  note text,
  updated_at timestamptz not null default now(),
  unique (session_id, player_id)
);

-- Aggiorna il constraint se esiste già una versione vecchia
alter table public.attendance_records
  drop constraint if exists attendance_records_status_check;

alter table public.attendance_records
  add constraint attendance_records_status_check
  check (status in (
    'present',
    'late',
    'absent_justified',
    'absent_unjustified',
    'injured',
    'sick',
    'riposo'
  ));

-- -------------------------
-- CHATS (mister-player)
-- -------------------------
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, player_id)
);

-- -------------------------
-- MESSAGES
-- -------------------------
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  text text not null,
  created_at timestamptz not null default now()
);

-- -------------------------
-- TEAM MISTERS (deleghe)
-- -------------------------
create table if not exists public.team_misters (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (team_id, user_id)
);

-- -------------------------
-- TEAM CHAT NICKNAMES
-- -------------------------
create table if not exists public.team_chat_nicknames (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  nickname text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, user_id)
);

create or replace function public.touch_chat_on_new_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.chats
  set updated_at = coalesce(new.created_at, now())
  where id = new.chat_id;

  return new;
end;
$$;

drop trigger if exists trg_touch_chat_on_new_message on public.messages;
create trigger trg_touch_chat_on_new_message
after insert on public.messages
for each row
execute function public.touch_chat_on_new_message();

-- -------------------------
-- INDICI
-- -------------------------
create index if not exists idx_teams_owner on public.teams(owner_user_id);
create index if not exists idx_players_team on public.players(team_id);
create index if not exists idx_fines_player on public.fines(player_id);
create index if not exists idx_fines_due on public.fines(is_paid, due_date);
create index if not exists idx_sessions_team_date on public.training_sessions(team_id, session_date desc);
create index if not exists idx_attendance_session on public.attendance_records(session_id);
create index if not exists idx_attendance_player on public.attendance_records(player_id);
create index if not exists idx_chats_team on public.chats(team_id);
create index if not exists idx_chats_player on public.chats(player_id);
create index if not exists idx_messages_chat on public.messages(chat_id);
create index if not exists idx_messages_created on public.messages(created_at desc);
create index if not exists idx_team_misters_team on public.team_misters(team_id);
create index if not exists idx_team_misters_user on public.team_misters(user_id);
create index if not exists idx_team_chat_nicknames_team on public.team_chat_nicknames(team_id);
create index if not exists idx_team_chat_nicknames_user on public.team_chat_nicknames(user_id);

-- =========================
-- HELPER FUNCTIONS (RLS)
-- =========================
create or replace function public.current_player_id()
returns bigint
language sql
stable
security definer
set search_path = public, auth
as $$
  select p.player_id
  from public.profiles p
  where p.id = auth.uid()
$$;

create or replace function public.current_player_team_id()
returns bigint
language sql
stable
security definer
set search_path = public, auth
as $$
  select pl.team_id
  from public.players pl
  where pl.id = public.current_player_id()
$$;

create or replace function public.is_team_owner(team bigint)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.teams t
    where t.id = team
      and t.owner_user_id = auth.uid()
    union all
    select 1
    from public.team_misters tm
    where tm.team_id = team
      and tm.user_id = auth.uid()
  )
$$;

drop function if exists public.join_team_as_mister(bigint, text);

create function public.join_team_as_mister(p_team_id bigint, p_password text)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if exists (
    select 1
    from public.teams t
    where t.id = p_team_id
      and t.mister_password is not null
      and t.mister_password = p_password
  ) then
    insert into public.team_misters (team_id, user_id)
    values (p_team_id, auth.uid())
    on conflict (team_id, user_id) do nothing;

    return true;
  end if;

  return false;
end;
$$;

revoke all on function public.join_team_as_mister(bigint, text) from public;
grant execute on function public.join_team_as_mister(bigint, text) to authenticated;

drop function if exists public.get_chat_sender_labels(bigint);

create function public.get_chat_sender_labels(p_chat_id bigint)
returns table (
  sender_id uuid,
  sender_label text
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_team_id bigint;
  v_player_id bigint;
begin
  select c.team_id, c.player_id
  into v_team_id, v_player_id
  from public.chats c
  where c.id = p_chat_id;

  if v_team_id is null or v_player_id is null then
    return;
  end if;

  -- 1) mister proprietario
  return query
  select
    t.owner_user_id::uuid as sender_id,
    coalesce(nullif(trim(tcn.nickname), ''), '1° Mister') as sender_label
  from public.teams t
  left join public.team_chat_nicknames tcn
    on tcn.team_id = t.id
   and tcn.user_id = t.owner_user_id
  where t.id = v_team_id;

  -- 2) mister delegati, in ordine di ingresso
  return query
  with ordered_misters as (
    select
      tm.user_id,
      row_number() over (order by tm.created_at asc) + 1 as mister_index
    from public.team_misters tm
    where tm.team_id = v_team_id
  )
  select
    om.user_id::uuid as sender_id,
    coalesce(nullif(trim(tcn.nickname), ''), (om.mister_index::text || '° Mister')) as sender_label
  from ordered_misters om
  left join public.team_chat_nicknames tcn
    on tcn.team_id = v_team_id
   and tcn.user_id = om.user_id;

  -- 3) giocatore della chat
  return query
  select
    pr.id::uuid as sender_id,
    'Giocatore' as sender_label
  from public.players pl
  left join public.profiles pr on pr.player_id = pl.id
  where pl.id = v_player_id;
end;
$$;

revoke all on function public.get_chat_sender_labels(bigint) from public;
grant execute on function public.get_chat_sender_labels(bigint) to authenticated;

drop function if exists public.get_joinable_team_players(bigint);

create function public.get_joinable_team_players(p_team_id bigint)
returns table (
  id bigint,
  name text,
  surname text,
  number text,
  "position" text,
  team_id bigint,
  team_name text,
  team_color text,
  created_at timestamptz,
  is_taken bigint,
  active_fines bigint,
  total_unpaid numeric
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    p.id,
    p.name,
    p.surname,
    p.number,
    p.position,
    p.team_id,
    t.name as team_name,
    t.color as team_color,
    p.created_at,
    case
      when exists (select 1 from public.profiles pr where pr.player_id = p.id) then 1::bigint
      else 0::bigint
    end as is_taken,
    (
      select count(*)::bigint
      from public.fines f
      where f.player_id = p.id
        and f.is_paid = false
    ) as active_fines,
    (
      select coalesce(sum(f.amount), 0)
      from public.fines f
      where f.player_id = p.id
        and f.is_paid = false
    ) as total_unpaid
  from public.players p
  left join public.teams t on t.id = p.team_id
  where p.team_id = p_team_id
  order by
    coalesce(nullif(lower(trim(p.surname)), ''), lower(trim(p.name))),
    lower(trim(p.name));
$$;

create or replace function public.delete_my_account()
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  delete from auth.users where id = auth.uid();
  return true;
exception
  when others then
    return false;
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;

-- =========================
-- RLS
-- =========================
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.players enable row level security;
alter table public.fines enable row level security;
alter table public.training_sessions enable row level security;
alter table public.attendance_records enable row level security;
alter table public.team_misters enable row level security;
alter table public.team_chat_nicknames enable row level security;

-- PROFILES
drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles for insert
to authenticated
with check (id = auth.uid());

-- TEAMS
drop policy if exists teams_select_authenticated on public.teams;
create policy teams_select_authenticated
on public.teams for select
to authenticated
using (true);

drop policy if exists teams_insert_owner on public.teams;
create policy teams_insert_owner
on public.teams for insert
to authenticated
with check (owner_user_id = auth.uid());

drop policy if exists teams_update_owner on public.teams;
create policy teams_update_owner
on public.teams for update
to authenticated
using (owner_user_id = auth.uid())
with check (owner_user_id = auth.uid());

drop policy if exists teams_delete_owner on public.teams;
create policy teams_delete_owner
on public.teams for delete
to authenticated
using (owner_user_id = auth.uid());

-- TEAM_MISTERS
drop policy if exists team_misters_select_related on public.team_misters;
create policy team_misters_select_related
on public.team_misters for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_team_owner(team_id)
  or team_id = public.current_player_team_id()
);

drop policy if exists team_misters_insert_owner_or_self on public.team_misters;
create policy team_misters_insert_owner_or_self
on public.team_misters for insert
to authenticated
with check (
  user_id = auth.uid()
  or public.is_team_owner(team_id)
);

drop policy if exists team_misters_delete_owner_or_self on public.team_misters;
create policy team_misters_delete_owner_or_self
on public.team_misters for delete
to authenticated
using (
  user_id = auth.uid()
  or public.is_team_owner(team_id)
);

-- TEAM CHAT NICKNAMES
drop policy if exists team_chat_nicknames_select_own on public.team_chat_nicknames;
create policy team_chat_nicknames_select_own
on public.team_chat_nicknames for select
to authenticated
using (user_id = auth.uid());

drop policy if exists team_chat_nicknames_insert_own on public.team_chat_nicknames;
create policy team_chat_nicknames_insert_own
on public.team_chat_nicknames for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists team_chat_nicknames_update_own on public.team_chat_nicknames;
create policy team_chat_nicknames_update_own
on public.team_chat_nicknames for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists team_chat_nicknames_delete_own on public.team_chat_nicknames;
create policy team_chat_nicknames_delete_own
on public.team_chat_nicknames for delete
to authenticated
using (user_id = auth.uid());

-- PLAYERS
drop policy if exists players_select_mister_or_same_team_player on public.players;
create policy players_select_mister_or_same_team_player
on public.players for select
to authenticated
using (
  public.is_team_owner(team_id)
  or team_id = public.current_player_team_id()
);

drop policy if exists players_insert_owner on public.players;
create policy players_insert_owner
on public.players for insert
to authenticated
with check (public.is_team_owner(team_id));

drop policy if exists players_update_owner on public.players;
create policy players_update_owner
on public.players for update
to authenticated
using (public.is_team_owner(team_id))
with check (public.is_team_owner(team_id));

drop policy if exists players_delete_owner on public.players;
create policy players_delete_owner
on public.players for delete
to authenticated
using (public.is_team_owner(team_id));

-- FINES
drop policy if exists fines_select_mister_or_self_player on public.fines;
create policy fines_select_mister_or_self_player
on public.fines for select
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and (
        public.is_team_owner(p.team_id)
        or p.team_id = public.current_player_team_id()
      )
  )
);

drop policy if exists fines_insert_owner on public.fines;
create policy fines_insert_owner
on public.fines for insert
to authenticated
with check (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
);

drop policy if exists fines_update_owner on public.fines;
create policy fines_update_owner
on public.fines for update
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
)
with check (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
);

drop policy if exists fines_delete_owner on public.fines;
create policy fines_delete_owner
on public.fines for delete
to authenticated
using (
  exists (
    select 1
    from public.players p
    where p.id = fines.player_id
      and public.is_team_owner(p.team_id)
  )
);

-- TRAINING SESSIONS
drop policy if exists sessions_select_mister_or_player_team on public.training_sessions;
create policy sessions_select_mister_or_player_team
on public.training_sessions for select
to authenticated
using (
  public.is_team_owner(team_id)
  or team_id = public.current_player_team_id()
);

drop policy if exists sessions_insert_owner on public.training_sessions;
create policy sessions_insert_owner
on public.training_sessions for insert
to authenticated
with check (
  public.is_team_owner(team_id)
  and created_by = auth.uid()
);

drop policy if exists sessions_update_owner on public.training_sessions;
create policy sessions_update_owner
on public.training_sessions for update
to authenticated
using (public.is_team_owner(team_id))
with check (public.is_team_owner(team_id));

drop policy if exists sessions_delete_owner on public.training_sessions;
create policy sessions_delete_owner
on public.training_sessions for delete
to authenticated
using (public.is_team_owner(team_id));

-- ATTENDANCE
drop policy if exists attendance_select_mister_or_self_player on public.attendance_records;
create policy attendance_select_mister_or_self_player
on public.attendance_records for select
to authenticated
using (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and (
        public.is_team_owner(s.team_id)
        or s.team_id = public.current_player_team_id()
      )
  )
);

drop policy if exists attendance_insert_owner on public.attendance_records;
create policy attendance_insert_owner
on public.attendance_records for insert
to authenticated
with check (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
);

drop policy if exists attendance_update_owner on public.attendance_records;
create policy attendance_update_owner
on public.attendance_records for update
to authenticated
using (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
)
with check (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
);

drop policy if exists attendance_delete_owner on public.attendance_records;
create policy attendance_delete_owner
on public.attendance_records for delete
to authenticated
using (
  exists (
    select 1
    from public.training_sessions s
    where s.id = attendance_records.session_id
      and public.is_team_owner(s.team_id)
  )
);

-- CHATS
drop policy if exists chats_select_mister_or_player on public.chats;
create policy chats_select_mister_or_player
on public.chats for select
to authenticated
using (
  public.is_team_owner(team_id)
  or exists (
    select 1
    from public.players p
    where p.id = chats.player_id
      and p.id = public.current_player_id()
  )
);

drop policy if exists chats_insert_mister on public.chats;
create policy chats_insert_mister
on public.chats for insert
to authenticated
with check (
  public.is_team_owner(team_id)
  or exists (
    select 1
    from public.players p
    where p.id = chats.player_id
      and p.id = public.current_player_id()
      and p.team_id = team_id
  )
);

drop policy if exists chats_update_mister_or_player on public.chats;
create policy chats_update_mister_or_player
on public.chats for update
to authenticated
using (
  public.is_team_owner(team_id)
  or exists (
    select 1
    from public.players p
    where p.id = chats.player_id
      and p.id = public.current_player_id()
  )
)
with check (
  public.is_team_owner(team_id)
  or exists (
    select 1
    from public.players p
    where p.id = chats.player_id
      and p.id = public.current_player_id()
  )
);

-- MESSAGES
drop policy if exists messages_select_participant on public.messages;
create policy messages_select_participant
on public.messages for select
to authenticated
using (
  exists (
    select 1
    from public.chats c
    where c.id = messages.chat_id
      and (
        public.is_team_owner(c.team_id)
        or exists (
          select 1
          from public.players p
          where p.id = c.player_id
            and p.id = public.current_player_id()
        )
      )
  )
);

drop policy if exists messages_insert_participant on public.messages;
create policy messages_insert_participant
on public.messages for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.chats c
    where c.id = messages.chat_id
      and (
        public.is_team_owner(c.team_id)
        or exists (
          select 1
          from public.players p
          where p.id = c.player_id
            and p.id = public.current_player_id()
        )
      )
  )
);

drop policy if exists messages_delete_own on public.messages;
create policy messages_delete_own
on public.messages for delete
to authenticated
using (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.chats c
    where c.id = messages.chat_id
      and (
        public.is_team_owner(c.team_id)
        or exists (
          select 1
          from public.players p
          where p.id = c.player_id
            and p.id = public.current_player_id()
        )
      )
  )
);

-- Enable RLS for new tables
alter table public.chats enable row level security;
alter table public.messages enable row level security;

-- =========================
-- STORAGE BUCKETS & POLICIES
-- =========================

-- Create team-logos bucket (public read, authenticated write)
insert into storage.buckets (id, name, public)
values ('team-logos', 'team-logos', true)
on conflict (id) do nothing;

drop policy if exists "Authenticated can upload team logos" on storage.objects;
drop policy if exists "Authenticated can update team logos" on storage.objects;
drop policy if exists "Authenticated can delete team logos" on storage.objects;
drop policy if exists "Public can read team logos" on storage.objects;

-- Allow authenticated users to upload team logos
create policy "Authenticated can upload team logos"
on storage.objects for insert
to authenticated
with check (bucket_id = 'team-logos');

-- Allow authenticated users to update their team logos
create policy "Authenticated can update team logos"
on storage.objects for update
to authenticated
using (bucket_id = 'team-logos')
with check (bucket_id = 'team-logos');

-- Allow authenticated users to delete their team logos
create policy "Authenticated can delete team logos"
on storage.objects for delete
to authenticated
using (bucket_id = 'team-logos');

-- Allow public read access to team logos
create policy "Public can read team logos"
on storage.objects for select
to public
using (bucket_id = 'team-logos');
